Repository WE-ARE-RACCOONS/postgraduate-back, pull requests merged in 2023-11, with the labels that each got.

#22 RAC-98 fix : RefreshToken 로직 수정 및 만료 시간 추가
  src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
  src/main/java/com/postgraduate/global/jwt/JwtFilter.java
  src/main/java/com/postgraduate/global/jwt/JwtProvider.java
Labels: 🐞 BugFix, ✨ Feature

#23 RAC-97 refactor : 사용자 정의 응답 코드 생성
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/payment/presentation/constant/PaymentResponseCode.java
  src/main/java/com/postgraduate/domain/review/presentation/constant/ReviewResponseCode.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/global/dto/ErrorResponse.java
  src/main/java/com/postgraduate/global/dto/ResponseDto.java
  src/main/java/com/postgraduate/global/exception/ApplicationException.java
  src/main/java/com/postgraduate/global/jwt/JwtProvider.java
Labels: 🛠️ Refactor

#24 RAC-100 feat : 프로필 사진 등록 및 멘토 회원가입
  build.gradle
  src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
  src/main/java/com/postgraduate/domain/auth/application/mapper/AuthMapper.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/image/application/dto/PreSignedUrlRequest.java
  src/main/java/com/postgraduate/domain/image/application/dto/PreSignedUrlResponse.java
  src/main/java/com/postgraduate/domain/image/application/usecase/PreSignedUseCase.java
  src/main/java/com/postgraduate/domain/image/presentation/ImageController.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseCode.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorSignUpUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorUpdateUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorSaveService.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateService.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/user/application/dto/req/UserProfileRequest.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserCheckUseCase.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserSaveService.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/global/config/s3/S3Config.java
  src/main/java/com/postgraduate/global/config/s3/S3Service.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
Labels: ✨ Feature, ⚙️ Setting

#25 RAC-102 feat: 대학생 관련 멘토링
  build.gradle
  src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
  src/main/java/com/postgraduate/domain/auth/application/mapper/AuthMapper.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/exception/AuthException.java
  src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/image/application/dto/PreSignedUrlRequest.java
  src/main/java/com/postgraduate/domain/image/application/dto/PreSignedUrlResponse.java
  src/main/java/com/postgraduate/domain/image/application/usecase/PreSignedUseCase.java
  src/main/java/com/postgraduate/domain/image/presentation/ImageController.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseCode.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseMessage.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringApplyRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringStatusRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringDetailResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringSaveService.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateService.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringException.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringNotFoundException.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorSignUpUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorUpdateUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorSaveService.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateService.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/user/application/dto/req/UserProfileRequest.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserCheckUseCase.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserSaveService.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/global/config/s3/S3Config.java
  src/main/java/com/postgraduate/global/config/s3/S3Service.java
  src/main/java/com/postgraduate/global/exception/ApplicationException.java
  src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
Labels: ✨ Feature

#28 RAC-107 대학원생 마이페이지 및 리펙토링
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorCertificationRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileAndAccountRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorInfoResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorProfileResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorSignUpUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorUpdateUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Account.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Status.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorSaveService.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateService.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
Labels: ✨ Feature, 🛠️ Refactor

#29 RAC-110 refactor : 카카오 로그인 code로 변경
  src/main/java/com/postgraduate/domain/auth/application/dto/req/KakaoCodeRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoTokenInfoResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/exception/AuthException.java
  src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringApplyRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringStatusRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringDetailResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringSaveService.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateService.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringException.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringNotFoundException.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/global/exception/ApplicationException.java
  src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
Labels: ✨ Feature, 🛠️ Refactor

#30 RAC-103 feat: 대학원생 멘토링 관련
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringDateRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringRefuseRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/SeniorMentoringDetailResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/SeniorMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateService.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringDoneException.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringNotWaitingException.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
Labels: ✨ Feature

#33 RAC-129 feat : 도메인 관련 예외 처리
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/exception/KakaoException.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/image/application/usecase/PreSignedUseCase.java
  src/main/java/com/postgraduate/domain/image/exception/EmptyFileException.java
  src/main/java/com/postgraduate/domain/image/exception/ImageException.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseCode.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/exception/NoneSeniorException.java
  src/main/java/com/postgraduate/domain/senior/exception/SeniorException.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/exception/NoneUserException.java
  src/main/java/com/postgraduate/domain/user/application/exception/UserException.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
Labels: ✨ Feature

#34 RAC-130 feat : Global 부분 예외 처리
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/exception/KakaoCodeException.java
  src/main/java/com/postgraduate/domain/auth/exception/KakaoException.java
  src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/exception/NotFoundUserException.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/global/auth/AuthDetailsService.java
  src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java
  src/main/java/com/postgraduate/global/jwt/JwtFilter.java
  src/main/java/com/postgraduate/global/jwt/JwtProvider.java
  src/main/java/com/postgraduate/global/jwt/constant/JwtResponseCode.java
  src/main/java/com/postgraduate/global/jwt/constant/JwtResponseMessage.java
  src/main/java/com/postgraduate/global/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/InvalidTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/JwtException.java
  src/main/java/com/postgraduate/global/jwt/exception/NoneRefreshTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/TokenExpiredException.java
  src/main/java/com/postgraduate/global/logging/dto/LogRequest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
Labels: 🐞 BugFix, ✨ Feature

#35 RAC-123 feat : 예외 처리 작업
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/exception/KakaoCodeException.java
  src/main/java/com/postgraduate/domain/auth/exception/KakaoException.java
  src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/image/application/usecase/PreSignedUseCase.java
  src/main/java/com/postgraduate/domain/image/exception/EmptyFileException.java
  src/main/java/com/postgraduate/domain/image/exception/ImageException.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseCode.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/exception/NoneSeniorException.java
  src/main/java/com/postgraduate/domain/senior/exception/SeniorException.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/exception/NotFoundUserException.java
  src/main/java/com/postgraduate/domain/user/application/exception/UserException.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/global/auth/AuthDetailsService.java
  src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java
  src/main/java/com/postgraduate/global/jwt/JwtFilter.java
  src/main/java/com/postgraduate/global/jwt/JwtProvider.java
  src/main/java/com/postgraduate/global/jwt/constant/JwtResponseCode.java
  src/main/java/com/postgraduate/global/jwt/constant/JwtResponseMessage.java
  src/main/java/com/postgraduate/global/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/InvalidTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/JwtException.java
  src/main/java/com/postgraduate/global/jwt/exception/NoneRefreshTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/TokenExpiredException.java
  src/main/java/com/postgraduate/global/logging/dto/LogRequest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
Labels: ✨ Feature

#37 RAC-124 test : 테스트 코드 작성
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorProfileResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorSignUpUseCase.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/global/auth/AuthDetails.java
  src/main/java/com/postgraduate/global/auth/AuthDetailsService.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/main/java/com/postgraduate/global/config/security/jwt/JwtFilter.java
  src/main/java/com/postgraduate/global/config/security/jwt/JwtProvider.java
  src/main/java/com/postgraduate/global/config/security/jwt/constant/JwtResponseCode.java
  src/main/java/com/postgraduate/global/config/security/jwt/constant/JwtResponseMessage.java
  src/main/java/com/postgraduate/global/config/security/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/com/postgraduate/global/config/security/jwt/exception/InvalidTokenException.java
  src/main/java/com/postgraduate/global/config/security/jwt/exception/JwtException.java
  src/main/java/com/postgraduate/global/config/security/jwt/exception/NoneRefreshTokenException.java
  src/main/java/com/postgraduate/global/config/security/jwt/exception/TokenExpiredException.java
  src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java
  src/main/java/com/postgraduate/global/jwt/exception/InvalidRefreshTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/InvalidTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/NoneRefreshTokenException.java
  src/main/java/com/postgraduate/global/jwt/exception/TokenExpiredException.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
  src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCaseTest.java
  src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java
Labels: 🛠️ Refactor, ✅ Test

#38 RAC-136 fix : 응답 코드 수정
  src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
Labels: 🐞 BugFix

#40 RAC-146 refactor : 변경된 요구사항 적용
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/DoneMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/ExpectedMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/WaitingMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileAndAccountRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorSignUpUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Account.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/dto/req/UserHopeRequest.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/entity/Hope.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
Labels: 🛠️ Refactor

#42 RAC-146 fix : 리팩토링에 의한 테스트코드 수정
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
  src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCaseTest.java
Labels: 🐞 BugFix

#43 RAC-146 refactor : 회원가입시 매칭 희망 여부 추가
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/postgraduate/domain/user/application/dto/req/UserHopeRequest.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/domain/entity/Hope.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
  src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCaseTest.java
Labels: 🛠️ Refactor

#41 RAC-138 feat: 관리자 기능 추가
  src/main/java/com/postgraduate/domain/admin/application/dto/CertificationInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/CertificationProfile.java
  src/main/java/com/postgraduate/domain/admin/application/dto/req/SeniorStatusRequest.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/CertificationDetailsResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/CertificationResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/MentoringResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/PaymentResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/SeniorResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/UserResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/UserWithSeniorResponse.java
  src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/PaymentManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SeniorManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/exception/SeniorException.java
  src/main/java/com/postgraduate/domain/admin/exception/SeniorNotWaitingException.java
  src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/DoneMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/ExpectedMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/WaitingMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
  src/main/java/com/postgraduate/domain/payment/presentation/constant/PaymentResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileAndAccountRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorSignUpUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Account.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/dto/req/UserHopeRequest.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/entity/Hope.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
  src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCaseTest.java
Labels: ✨ Feature

#46 RAC-153 fix : 수정에 의한 테스트 빌드 실패 해결
  src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java
Labels: 🐞 BugFix

#51 RAC-158 feat : 매일 자정 기간 지난 멘토링 신청 자동 취소
  src/main/java/com/postgraduate/PostgraduateApplication.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
Labels: ✨ Feature

#54 RAC-169 fix : 변경된 요구사항 적용
  src/main/java/com/postgraduate/domain/account/domain/entity/Account.java
  src/main/java/com/postgraduate/domain/account/domain/service/AccountUpdateService.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageUserAccountRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageProfileResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageUserAccountResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateService.java
  src/main/java/com/postgraduate/domain/senior/exception/NoneAccountException.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/JwtFilter.java
Labels: 🐞 BugFix, ✨ Feature

#55 RAC 180 fix: 대학생 구현 점검
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedDoneMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedExpectedMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedWaitingMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/user/application/exception/NotFoundUserException.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/exception/UserException.java
  src/main/java/com/postgraduate/domain/user/exception/UserNotFoundException.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/global/auth/AuthDetailsService.java
  src/main/java/com/postgraduate/global/config/security/jwt/JwtProvider.java
Labels: 🐞 BugFix, 🛠️ Refactor

#59 RAC-155 feat : 멘토 검색 기능 구현
  src/main/java/com/postgraduate/domain/account/application/mapper/AccountMapper.java
  src/main/java/com/postgraduate/domain/account/domain/entity/Account.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/AllSeniorSearchResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorSearchResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
Labels: 🐞 BugFix, ✨ Feature

#60 RAC-184 feat : S3 업로드 백엔드 구현
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SeniorChangeRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SeniorSignUpRequest.java
  src/main/java/com/postgraduate/domain/image/application/dto/req/PreSignedUrlRequest.java
  src/main/java/com/postgraduate/domain/image/application/dto/res/ImageUrlResponse.java
  src/main/java/com/postgraduate/domain/image/application/dto/res/PreSignedUrlResponse.java
  src/main/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCase.java
  src/main/java/com/postgraduate/domain/image/application/usecase/PreSignedUseCase.java
  src/main/java/com/postgraduate/domain/image/exception/DeleteException.java
  src/main/java/com/postgraduate/domain/image/exception/UploadException.java
  src/main/java/com/postgraduate/domain/image/presentation/ImageController.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseCode.java
  src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageUserAccountResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/global/config/s3/S3UploadService.java
Labels: ✨ Feature
