Repository WE-ARE-RACCOONS/postgraduate-back, pull requests merged in 2023-12, with the labels that each got.

#61 RAC-185 feat : 대학원생 분야 필터 추가
  src/main/java/com/postgraduate/domain/senior/application/dto/res/AllSeniorFieldResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorFieldResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorSearchResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Field.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Postgradu.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/user/application/dto/res/UserPossibleResponse.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
Labels: ✨ Feature, 🛠️ Refactor

#63 RAC-129 refactor : 기존 구현 점검 및 수정 사항 적용
  src/main/java/com/postgraduate/domain/auth/application/dto/req/CodeRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/KakaoCodeRequest.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/SignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SelectOauth.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/exception/OauthException.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/DoneMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/DoneSeniorMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/ExpectedMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/ExpectedSeniorMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/WaitingMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/WaitingSeniorMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/res/SeniorMentoringDetailResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/refuse/application/mapper/RefuseMapper.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorAccountRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageUserAccountResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorProfileResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
Labels: 🐞 BugFix, ✨ Feature, 🛠️ Refactor

#64 RAC-223 : 로그아웃 추가
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SelectOauth.java
  src/main/java/com/postgraduate/domain/auth/exception/KakaoCodeException.java
  src/main/java/com/postgraduate/domain/auth/exception/KakaoException.java
  src/main/java/com/postgraduate/domain/auth/exception/OauthException.java
  src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseCode.java
  src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/auth/presentation/constant/Provider.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/main/java/com/postgraduate/global/config/security/jwt/constant/Type.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/JwtFilter.java
  src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
  src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java
Labels: 🐞 BugFix, ✨ Feature

#65 RAC-187 fix: 유효성 검사
  build.gradle
  src/main/java/com/postgraduate/domain/account/application/mapper/AccountMapper.java
  src/main/java/com/postgraduate/domain/admin/application/dto/req/SeniorStatusRequest.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SeniorManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
  src/main/java/com/postgraduate/domain/admin/presentation/constant/AdminResponseCode.java
  src/main/java/com/postgraduate/domain/admin/presentation/constant/AdminResponseMessage.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringApplyRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/salary/application/dto/SalaryDetails.java
  src/main/java/com/postgraduate/domain/salary/application/dto/res/SalaryDetailResponse.java
  src/main/java/com/postgraduate/domain/salary/application/dto/res/SalaryDetailsResponse.java
  src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
  src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCase.java
  src/main/java/com/postgraduate/domain/salary/presentation/SalaryController.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorAccountRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorCertificationRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorDetailResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageProfileResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/user/application/dto/res/UserInfoResponse.java
  src/main/java/com/postgraduate/domain/user/application/dto/res/UserMyPageResponse.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/domain/wish/application/mapper/WishMapper.java
Labels: 🛠️ Refactor

#68 RAC-230 feat : 회원 탈퇴 기본 로직 구현
  src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoTokenInfoResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SelectOauth.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignOutUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
Labels: ✨ Feature

#69 RAC-231 fix : 탈퇴 회원 고려 조회 로직 수정
  src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/user/exception/DeletedUserException.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/domain/wish/domain/repository/WishRepository.java
  src/main/java/com/postgraduate/domain/wish/domain/service/WishGetService.java
Labels: 🐞 BugFix, 🛠️ Refactor

#70 RAC-224 fix : 회원 탈퇴 로직 추가 및 기존 조회 수정
  src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoTokenInfoResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SelectOauth.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignOutUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/exception/DeletedUserException.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/domain/wish/domain/repository/WishRepository.java
  src/main/java/com/postgraduate/domain/wish/domain/service/WishGetService.java
Labels: 🐞 BugFix, ✨ Feature, 🛠️ Refactor

#71 RAC-232 fix : 기존 대학원생 가능 시간 정보 로직 수정
  src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
  src/main/java/com/postgraduate/domain/available/application/dto/req/AvailableCreateRequest.java
  src/main/java/com/postgraduate/domain/available/application/dto/res/AvailableTimeResponse.java
  src/main/java/com/postgraduate/domain/available/application/dto/res/AvailableTimesResponse.java
  src/main/java/com/postgraduate/domain/available/application/mapper/AvailableMapper.java
  src/main/java/com/postgraduate/domain/available/domain/entity/Available.java
  src/main/java/com/postgraduate/domain/available/domain/repository/AvailableRepository.java
  src/main/java/com/postgraduate/domain/available/domain/service/AvailableDeleteService.java
  src/main/java/com/postgraduate/domain/available/domain/service/AvailableGetService.java
  src/main/java/com/postgraduate/domain/available/domain/service/AvailableSaveService.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorDetailResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageProfileResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorSearchResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
Labels: 🐞 BugFix, ✨ Feature, 🛠️ Refactor

#67 RAC-222 fix: 데이터 타입 변경
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
Labels: 🛠️ Refactor

#72 RAC-233 test : UseCase 테스트 코드 작성
  src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoUserInfoResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/available/application/util/AvailableUtil.java
  src/main/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringNotExpectedException.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCaseTest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SelectOauthTest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCaseTest.java
  src/test/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
  src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCaseTest.java
  src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java
Labels: ✨ Feature, 🛠️ Refactor, ✅ Test

#73 RAC-242 fix : 선배 계정 설정시 계좌 포함 필수 유동적으로 수정
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageUserAccountRequest.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
Labels: 🐞 BugFix

#75 RAC-246 fix : 기본 이미지 설정
  src/main/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCase.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/global/config/s3/Default.java
Labels: 🛠️ Refactor

#76 RAC-246 test : 기본 이미지 변경 테스트 수정
  src/test/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCaseTest.java
Labels: 🐞 BugFix, ✅ Test

#77 RAC-248 feat : 선배가 후배로 변경하는 경우 로직 추가 및 기존 로직 변경
  src/main/java/com/postgraduate/domain/auth/application/dto/req/UserChangeRequest.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorPossibleResponse.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/wish/application/mapper/WishMapper.java
  src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCaseTest.java
Labels: ✨ Feature, 🛠️ Refactor

#74 RAC-234 fix: 관리자 점검
  src/main/java/com/postgraduate/domain/admin/application/dto/MentoringInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/PaymentInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/UserInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/UserMentoringInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/CertificationDetailsResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/MentoringManageResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/PaymentManageResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/SalaryManageResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/SeniorManageResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/UserManageResponse.java
  src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/PaymentManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SeniorManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/constant/Status.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
  src/main/java/com/postgraduate/domain/salary/application/dto/SeniorSalary.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepository.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryRepository.java
  src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
  src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/wish/application/mapper/dto/res/WishResponse.java
  src/main/java/com/postgraduate/domain/wish/domain/repository/WishDslRepository.java
  src/main/java/com/postgraduate/domain/wish/domain/repository/WishDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/wish/domain/repository/WishRepository.java
  src/main/java/com/postgraduate/domain/wish/domain/service/WishGetService.java
Labels: ✨ Feature, 🛠️ Refactor

#79 RAC-238 test : 서비스 테스트 코드 작성
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/test/java/com/postgraduate/domain/account/domain/service/AccountUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetServiceTest.java
  src/test/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/payment/domain/service/PaymentGetServiceTest.java
  src/test/java/com/postgraduate/domain/salary/domain/service/SalaryGetServiceTest.java
  src/test/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/domain/service/SeniorGetServiceTest.java
  src/test/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/user/domain/service/UserGetServiceTest.java
  src/test/java/com/postgraduate/domain/user/domain/service/UserUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/wish/domain/service/WishGetServiceTest.java
Labels: 🛠️ Refactor, ✅ Test

#81 RAC-240 refactor : 로그 저장 방식 변경
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java
  src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
  src/main/java/com/postgraduate/global/logging/aop/LogAspect.java
  src/main/java/com/postgraduate/global/logging/aop/LogTrace.java
  src/main/java/com/postgraduate/global/logging/aop/LogUtils.java
  src/main/java/com/postgraduate/global/logging/aop/TraceStatus.java
  src/main/java/com/postgraduate/global/logging/dto/LogRequest.java
Labels: 🛠️ Refactor

#80 RAC-249 feat: 매칭 기능
  src/main/java/com/postgraduate/domain/admin/application/dto/UserInfo.java
  src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
  src/main/java/com/postgraduate/domain/admin/presentation/constant/AdminResponseMessage.java
  src/main/java/com/postgraduate/domain/wish/application/mapper/WishMapper.java
  src/main/java/com/postgraduate/domain/wish/domain/entity/Wish.java
  src/main/java/com/postgraduate/domain/wish/domain/entity/constant/Status.java
  src/main/java/com/postgraduate/domain/wish/domain/service/WishUpdateService.java
  src/main/java/com/postgraduate/domain/wish/exception/MatchingNotReceiveException.java
  src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseCode.java
  src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseMessage.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
Labels: ✨ Feature

#82 RAC-250 fix : 전체 점검 및 수정
  src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
  src/main/java/com/postgraduate/domain/auth/application/mapper/AuthMapper.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringDateException.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/utils/SeniorUtils.java
  src/main/java/com/postgraduate/domain/senior/exception/KeywordException.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/com/postgraduate/domain/user/application/utils/UserUtils.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/exception/PhoneNumberException.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/utils/SeniorUtilsTest.java
  src/test/java/com/postgraduate/domain/user/application/usecase/UserManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/user/application/utils/UserUtilsTest.java
Labels: 🐞 BugFix, ✨ Feature, ✅ Test

#83 RAC-264 refactor : fetch LAZY 설정
  src/main/java/com/postgraduate/domain/account/domain/entity/Account.java
  src/main/java/com/postgraduate/domain/available/domain/entity/Available.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/refuse/domain/entity/Refuse.java
  src/main/java/com/postgraduate/domain/review/domain/entity/Review.java
  src/main/java/com/postgraduate/domain/salary/domain/entity/Salary.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/wish/domain/entity/Wish.java
Labels: 🛠️ Refactor
