Repository WE-ARE-RACCOONS/postgraduate-back, pull requests merged in 2023-10, with the labels that each got.

#8 RAC-79 feat : 카카오 로그인 연동
  build.gradle
  src/main/java/com/postgraduate/domain/auth/application/dto/KakaoAccessTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/dto/KakaoLoginRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/KakaoUserInfoResponse.java
  src/main/java/com/postgraduate/domain/auth/application/mapper/AuthMapper.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/repository/UserRepository.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserSaveService.java
  src/main/java/com/postgraduate/global/config/webclient/WebClientConfig.java
Labels: ✨ Feature, ⚙️ Setting

#9 RAC-85 feat: JWT 로그인
  src/main/java/com/postgraduate/domain/auth/application/dto/AuthUserResponse.java
  src/main/java/com/postgraduate/domain/auth/application/dto/JwtTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/review/domain/entity/Review.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/entity/constant/Role.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/global/auth/AuthDetails.java
  src/main/java/com/postgraduate/global/auth/AuthDetailsService.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/main/java/com/postgraduate/global/jwt/JwtFilter.java
  src/main/java/com/postgraduate/global/jwt/JwtProvider.java
Labels: ✨ Feature, ⚙️ Setting

#10 RAC-66 feat : workflow 작성
  .github/workflows/CD-develop.yml
Labels: ⚙️ Setting

#14 Rac 80 feat: 회원가입 진행
  .github/workflows/CD-develop.yml
  Dockerfile
  src/main/java/com/postgraduate/domain/auth/application/dto/req/KakaoLoginRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoAccessTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoUserInfoResponse.java
  src/main/java/com/postgraduate/domain/auth/application/mapper/AuthMapper.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserCheckUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/repository/UserRepository.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserSaveService.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java
Labels: ✨ Feature

#13 RAC-83 feat : 멘토링 일부 및 대학생 마이페이지 작업
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringDetailResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/review/domain/entity/Review.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/user/application/dto/req/UserNickNameRequest.java
  src/main/java/com/postgraduate/domain/user/application/dto/res/UserInfoResponse.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java
Labels: ✨ Feature

#18 RAC-83 fix : 토큰 관련 수정 및 Cors수정
  src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringDetailResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/entity/constant/Role.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/global/config/redis/RedisRepository.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/main/java/com/postgraduate/global/jwt/JwtProvider.java
Labels: 🐞 BugFix, ⚙️ Setting

#20 RAC-83 fix : Cors 수정
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
Labels: 🐞 BugFix, ⚙️ Setting

#15 RAC-81 feat: 대학원생 추가 정보 입력
  src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringDetailResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringInfo.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringResponse.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/review/domain/entity/Review.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorSignUpRequest.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorSignUpUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorUpdateUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorSaveService.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/dto/req/UserNickNameRequest.java
  src/main/java/com/postgraduate/domain/user/application/dto/res/UserInfoResponse.java
  src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/domain/user/domain/entity/constant/Role.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
  src/main/java/com/postgraduate/domain/user/presentation/UserController.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
  src/main/java/com/postgraduate/global/config/redis/RedisRepository.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java
  src/main/java/com/postgraduate/global/config/swagger/SwaggerConfig.java
  src/main/java/com/postgraduate/global/jwt/JwtProvider.java
Labels: ✨ Feature
