Repository WE-ARE-RACCOONS/postgraduate-back, pull requests merged in 2024-01, with the labels that each got.

#84 RAC-251 fix: 전체점검
  src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
  src/main/java/com/postgraduate/domain/admin/presentation/constant/AdminResponseMessage.java
  src/main/java/com/postgraduate/domain/available/application/dto/res/AvailableTimesResponse.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentUpdateService.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/AllSeniorSearchResponse.java
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorProfileResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/wish/application/mapper/dto/res/WishResponse.java
  src/main/java/com/postgraduate/domain/wish/domain/repository/WishRepository.java
  src/main/java/com/postgraduate/domain/wish/domain/service/WishGetService.java
  src/main/java/com/postgraduate/domain/wish/exception/WishEmptyException.java
  src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseCode.java
  src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseMessage.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
Labels: 🐞 BugFix, ✨ Feature

#86 RAC-274 deploy : CI/CD 분리 및 jdk 경량화 버전 사용
  .github/workflows/CI-develop.yml
  Dockerfile
Labels: 🌍 Deploy

#87 RAC-257 feat : 결제 기능 추가 및 리팩토링
  src/main/java/com/postgraduate/domain/admin/application/dto/SalaryInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/UserMentoringInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/SalaryDetailsResponse.java
  src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SeniorManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/presentation/constant/SalaryStatus.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SeniorSignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringDetailNotFoundException.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringDoneException.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/payment/application/dto/req/PaymentResultRequest.java
  src/main/java/com/postgraduate/domain/payment/application/mapper/PaymentMapper.java
  src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentSaveService.java
  src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java
  src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
  src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCase.java
  src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryManageUseCase.java
  src/main/java/com/postgraduate/domain/salary/domain/entity/Salary.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepository.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryRepository.java
  src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
  src/main/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateService.java
  src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/payment/domain/service/PaymentGetServiceTest.java
  src/test/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/salary/domain/service/SalaryGetServiceTest.java
  src/test/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
Labels: ✨ Feature, 🛠️ Refactor, ✅ Test

#89 RAC-257 feat : 결제 기능 추가 및 리팩토링"
  src/main/java/com/postgraduate/domain/admin/application/dto/SalaryInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/UserMentoringInfo.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/SalaryDetailsResponse.java
  src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/SeniorManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/presentation/constant/SalaryStatus.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SeniorSignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepository.java
  src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringDetailNotFoundException.java
  src/main/java/com/postgraduate/domain/mentoring/exception/MentoringDoneException.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/payment/application/dto/req/PaymentResultRequest.java
  src/main/java/com/postgraduate/domain/payment/application/mapper/PaymentMapper.java
  src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentSaveService.java
  src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java
  src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
  src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCase.java
  src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryManageUseCase.java
  src/main/java/com/postgraduate/domain/salary/domain/entity/Salary.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepository.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryRepository.java
  src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
  src/main/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateService.java
  src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/payment/domain/service/PaymentGetServiceTest.java
  src/test/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/salary/domain/service/SalaryGetServiceTest.java
  src/test/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateServiceTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
Labels: ✨ Feature, 🛠️ Refactor, ✅ Test

#92 RAC-277 refactor : 수정 및 편의 사항 추가
  build.gradle
  src/main/java/com/postgraduate/domain/admin/application/dto/req/PaymentResultRequest.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/CertificationResponse.java
  src/main/java/com/postgraduate/domain/admin/application/dto/res/RefundResponse.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/PaymentManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringDeleteService.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
  src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
  src/main/java/com/postgraduate/domain/payment/application/mapper/PaymentMapper.java
  src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
  src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
  src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
  src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java
  src/main/java/com/postgraduate/domain/salary/application/dto/SeniorAndAccount.java
  src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
  src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryManageUseCase.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepository.java
  src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
  src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
  src/main/java/com/postgraduate/global/logging/service/LogService.java
  src/main/java/com/postgraduate/global/mq/config/RabbitMQConfig.java
  src/main/java/com/postgraduate/global/slack/SlackMessage.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
  src/test/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCaseTest.java
Labels: 🐞 BugFix, ✨ Feature, 🛠️ Refactor

#95 RAC-288 fix : socialId 추가(프론트 요구사항)
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorPossibleResponse.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
Labels: 🐞 BugFix

#96 RAC-288 feat : seniorId 리스트 조회 추가
  src/main/java/com/postgraduate/domain/senior/application/dto/res/AllSeniorIdResponse.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
  src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
Labels: ✨ Feature

#97 RAC-288 feat : 개발용 소셜 로그인 추가
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
  src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
Labels: ✨ Feature

#93 RAC-254 test: 통합테스트
  src/main/java/com/postgraduate/domain/available/application/util/AvailableUtil.java
  src/main/java/com/postgraduate/domain/available/exception/DayAvailableException.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepositoryImpl.java
  src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageProfileRequest.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
  src/main/java/com/postgraduate/domain/senior/exception/NoneProfileException.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
  src/test/java/com/postgraduate/domain/salary/presentation/SalaryControllerTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
  src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java
Labels: ✅ Test

#98 RAC-292 feat : log 파일 생성
  .github/workflows/CD-develop.yml
  .github/workflows/CI-develop.yml
  src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
  src/main/java/com/postgraduate/global/logging/aop/LogAspect.java
  src/main/java/com/postgraduate/global/logging/aop/LogTrace.java
  src/main/java/com/postgraduate/global/mq/producer/MessageProducer.java
  src/main/resources/logback-spring.xml
Labels: ✨ Feature

#99 RAC-292 fix : logback 수정
  src/main/resources/logback-spring.xml
Labels: 🐞 BugFix

#100 RAC-288 feat : 선배 상세조회 본인 여부 확인 추가
  src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorDetailResponse.java
  src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
Labels: ✨ Feature

#101 RAC-286 fix: 코드 통일
  src/main/java/com/postgraduate/domain/account/domain/service/AccountSaveService.java
  src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
  src/main/java/com/postgraduate/domain/admin/exception/SeniorNotWaitingException.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SeniorSignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
  src/main/java/com/postgraduate/domain/auth/application/dto/req/UserChangeRequest.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
  src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
  src/main/java/com/postgraduate/domain/auth/exception/OauthException.java
  src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseCode.java
  src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseMessage.java
  src/main/java/com/postgraduate/domain/available/exception/EmptyAvailableException.java
  src/main/java/com/postgraduate/domain/image/application/dto/req/PreSignedUrlRequest.java
  src/main/java/com/postgraduate/domain/image/application/dto/res/PreSignedUrlResponse.java
  src/main/java/com/postgraduate/domain/image/application/usecase/PreSignedUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringApplyRequest.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
  src/main/java/com/postgraduate/domain/refuse/domain/service/RefuseSaveService.java
  src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryManageUseCase.java
  src/main/java/com/postgraduate/domain/salary/domain/service/SalarySaveService.java
  src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
  src/main/java/com/postgraduate/domain/senior/exception/NoneAccountException.java
  src/main/java/com/postgraduate/domain/senior/exception/NoneProfileException.java
  src/main/java/com/postgraduate/domain/senior/exception/NoneSeniorException.java
  src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
  src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
  src/main/java/com/postgraduate/domain/user/application/usecase/UserManageUseCase.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
  src/main/java/com/postgraduate/domain/user/domain/service/UserSaveService.java
  src/main/java/com/postgraduate/domain/user/exception/DeletedUserException.java
  src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
  src/main/java/com/postgraduate/domain/wish/domain/service/WishSaveService.java
  src/main/java/com/postgraduate/domain/wish/exception/MatchingNotReceiveException.java
  src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseCode.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
  src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java
  src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
  src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
  src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java
  src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
  src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
  src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
  src/test/java/com/postgraduate/domain/user/domain/service/UserGetServiceTest.java
Labels: 🛠️ Refactor

#102 RAC-304 fix : 비로그인 상태 선배 상세조회 가능하도록 수정
  src/main/java/com/postgraduate/domain/user/domain/entity/User.java
  src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
Labels: 🐞 BugFix

#103 RAC-304 fix : 멘토링 기본 시간 조정 및 확인용 로그 추가
  src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
  src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
  src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
Labels: 🐞 BugFix
